<!DOCTYPE html>
<html>
<head>
<!--<meta http-equiv="pragma" content="no-cache" />
<meta http-equiv="cache-control" content="no-cache" />-->
<meta name="robots" content="noindex,nofollow" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="Content-Script-Type" content="text/javascript" />
<meta http-equiv="Content-Style-Type" content="text/css" />
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" type="text/css" href="/mvc3/css/bootstrap.min.css" media="screen">
<title><?=$title?></title>
<meta http-equiv="X-FRAME-OPTIONS" content="SAMEORIGIN" />
<link rel="StyleSheet" type="text/css" href="/mvc3/css/default.css">
<?php
if(isset($styles)){
	foreach ($styles as $val){
		echo '<link rel="StyleSheet" type="text/css" href="/mvc3/css/'. $val .'.css">';
	}
}
?>
</head>
<body>